module ConfigX
  class Config
    def initialize: (Hash[untyped, untyped]) -> void

    def to_h: -> Hash[untyped, untyped]

    def with_fallback: (Config) -> Config

    def each_pair: -> Enumerable[[untyped, untyped]]

    def []=: (untyped, untyped) -> untyped
  end
end
