module ConfigX
  class ConfigFactory
    def self.default_config_root: -> String

    def self.default_dir_name: -> String

    def self.default_env_prefix: -> String

    def self.default_env_separator: -> String

    def self.default_env: -> String

    def self.default_file_name: -> String

    def self.load: (
        String env,
        env_prefix: String,
        env_separator: String,
        dir_name: String,
        file_name: String,
        config_root: String
      ) -> Config

    def initialize: (
        String env,
        env_prefix: String,
        env_separator: String,
        dir_name: String,
        file_name: String,
        config_root: String
      ) -> void

    def load: -> Config

    private

    def local_setting_files: -> Array[String]

    def setting_files: -> Array[String]

    attr_reader config_root: String

    attr_reader dir_name: String

    attr_reader env_prefix: String

    attr_reader env_separator: String

    attr_reader env: String

    attr_reader file_name: String

    def sources: -> Array[Builder::source]
  end
end
