
module ConfigX
  class HashSource < Source
    def self.deep_stringify_keys: [T] (Hash[(String | Symbol), T])-> Hash[String, T]

    def initialize: (Source::config_hash) -> void

    attr_reader source: Source::config_hash
  end
end
